arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.614571', '20.339251', '18.009439', '19.340992', '8.517027', '26.570261', '23.352191', '24.498761', '15.517473', '33.697635', '30.156612', '31.473458', '22.454500', '39.088875', '35.152256', '36.585093', '29.431105', '46.088755', '42.479485', '43.779910', '36.393523', '53.180695', '48.173547', '49.119800', '43.302059', '58.491349', '53.052485', '54.266512', '50.292015', '64.650238', '59.229016', '60.567737', '57.282567', '70.928276', '66.366553', '67.521274', '64.346433', '75.295269', '71.010053', '72.279334']
reference_Device: [1.614571, 8.517027, 15.517473, 22.4545, 29.431105, 36.393523, 43.302059, 50.292015, 57.282567, 64.346433]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_0/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.613498', '20.103246', '17.944112', '19.232258', '8.564591', '27.383536', '24.242759', '25.337338', '15.532374', '33.569634', '30.227005', '31.347007', '22.460580', '39.352119', '35.297871', '36.739379', '29.418468', '45.072138', '41.334033', '42.527497', '36.343575', '52.458704', '47.109276', '48.243642', '43.357491', '59.368551', '54.137290', '55.328012', '50.312042', '65.163732', '60.000777', '61.066806', '57.239532', '69.981039', '65.447986', '66.597223', '64.210415', '76.383948', '72.131455', '73.258460']
reference_Device: [1.613498, 8.564591, 15.532374, 22.46058, 29.418468, 36.343575, 43.357491, 50.312042, 57.239532, 64.210415]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_1/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.638532', '20.300493', '18.152863', '19.517884', '8.532047', '26.664138', '23.281321', '24.633631', '15.483975', '32.937855', '29.378235', '30.738264', '22.495031', '39.968580', '36.182374', '37.461370', '29.401779', '45.177132', '41.520774', '42.837888', '36.350369', '53.094208', '47.321141', '48.455268', '43.340564', '59.247255', '53.790510', '55.018544', '50.297141', '64.982772', '59.835494', '61.057031', '57.239532', '70.074558', '65.278232', '66.554785', '64.185977', '75.806737', '71.798682', '72.743058']
reference_Device: [1.638532, 8.532047, 15.483975, 22.495031, 29.401779, 36.350369, 43.340564, 50.297141, 57.239532, 64.185977]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_2/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.626492', '20.208195', '18.116996', '19.438744', '8.570313', '27.410567', '24.307996', '25.461465', '15.527010', '33.781737', '30.159146', '31.470388', '22.484541', '39.768994', '35.898149', '37.321508', '29.386044', '44.870138', '41.139334', '42.434245', '36.394477', '53.158104', '48.484981', '49.368143', '43.367147', '59.331954', '53.937018', '55.092275', '50.307274', '64.899862', '59.722960', '61.015546', '57.261109', '70.775688', '66.267490', '67.424536', '64.203024', '76.322794', '72.191060', '73.380768']
reference_Device: [1.626492, 8.570313, 15.52701, 22.484541, 29.386044, 36.394477, 43.367147, 50.307274, 57.261109, 64.203024]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_3/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.731515', '22.215143', '19.899607', '21.355510', '8.527756', '26.717007', '23.536056', '24.750367', '15.622020', '35.511762', '31.955004', '33.256978', '22.492051', '39.853632', '36.057740', '37.394255', '29.432178', '45.795619', '42.031586', '43.414831', '36.394596', '53.234220', '48.416018', '49.182057', '43.299556', '58.516860', '53.011477', '54.183424', '50.279498', '64.358771', '59.081316', '60.326457', '57.228565', '70.034027', '65.454423', '66.556275', '64.231873', '76.072812', '71.952343', '73.132753']
reference_Device: [1.731515, 8.527756, 15.62202, 22.492051, 29.432178, 36.394596, 43.299556, 50.279498, 57.228565, 64.231873]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_4/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.569867', '19.418865', '17.245010', '18.862680', '8.534431', '26.681274', '23.411617', '24.605945', '15.545607', '33.896238', '30.338883', '31.696737', '22.477984', '39.983004', '36.025524', '37.377626', '29.454589', '45.634598', '42.093635', '43.460906', '36.348581', '52.485347', '47.289640', '48.403472', '43.314338', '58.710992', '53.232729', '54.485977', '50.332069', '65.325797', '59.973717', '61.280787', '57.240129', '69.938183', '65.324247', '66.677034', '64.223528', '76.289058', '72.039783', '73.230505']
reference_Device: [1.569867, 8.534431, 15.545607, 22.477984, 29.454589, 36.348581, 43.314338, 50.332069, 57.240129, 64.223528]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_5/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.620054', '20.180687', '17.988458', '19.438192', '8.524418', '26.611626', '23.299202', '24.484694', '15.500546', '33.137381', '29.418975', '30.683249', '22.464514', '39.122850', '35.249144', '36.593854', '29.431939', '45.634657', '42.055637', '43.326378', '36.409378', '53.362012', '48.491001', '49.391121', '43.302536', '58.480978', '53.238809', '54.592490', '50.302863', '65.004766', '59.755027', '61.173320', '57.225943', '69.737494', '65.066278', '66.280425', '64.173460', '75.475752', '71.062982', '72.332799']
reference_Device: [1.620054, 8.524418, 15.500546, 22.464514, 29.431939, 36.409378, 43.302536, 50.302863, 57.225943, 64.17346]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_6/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.578450', '19.387498', '17.171934', '18.530011', '8.565664', '27.267992', '24.062708', '25.216490', '15.503407', '33.075392', '29.419214', '30.741334', '22.454500', '39.096534', '35.248369', '36.626667', '29.399991', '45.096397', '41.405290', '42.766899', '36.357999', '52.384675', '47.102779', '48.231512', '43.341041', '59.485972', '53.996980', '55.152535', '50.310969', '65.324306', '60.046971', '61.289251', '57.232380', '70.098042', '65.294504', '66.528022', '64.214587', '76.258302', '71.961522', '73.246777']
reference_Device: [1.57845, 8.565664, 15.503407, 22.4545, 29.399991, 36.357999, 43.341041, 50.310969, 57.23238, 64.214587]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_7/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.574397', '19.317940', '17.311633', '18.627137', '8.569479', '27.317554', '24.150446', '25.396883', '15.459538', '32.847971', '29.321283', '30.513704', '22.502065', '40.049136', '35.879374', '37.231624', '29.450536', '45.719624', '41.895747', '43.174237', '36.402583', '53.266346', '48.233747', '49.185127', '43.331981', '59.337020', '53.830266', '55.796742', '50.325513', '65.454423', '60.058534', '61.298966', '57.276011', '70.794284', '66.052377', '67.115784', '64.211488', '76.149285', '71.936965', '73.076487']
reference_Device: [1.574397, 8.569479, 15.459538, 22.502065, 29.450536, 36.402583, 43.331981, 50.325513, 57.276011, 64.211488]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_8/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.622915', '20.071700', '17.881244', '19.217566', '8.563042', '27.429372', '24.379283', '25.482148', '15.595078', '35.469383', '31.904012', '33.179849', '22.490978', '39.827377', '36.042362', '37.391812', '29.443622', '45.839459', '42.074502', '43.348730', '36.359429', '52.543759', '47.642916', '48.775375', '43.441415', '61.271548', '55.848002', '57.242990', '50.324082', '65.088332', '59.879541', '60.981214', '57.267070', '70.730031', '66.216767', '67.137957', '64.209938', '76.230466', '71.937799', '73.200524']
reference_Device: [1.622915, 8.563042, 15.595078, 22.490978, 29.443622, 36.359429, 43.441415, 50.324082, 57.26707, 64.209938]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 172, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 83, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/27_9/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 5590366 ON r2i7n3 CANCELLED AT 2024-04-04T19:37:14 ***
slurmstepd: error: *** STEP 5590366.105 ON r2i7n3 CANCELLED AT 2024-04-04T19:37:14 ***
