arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.575470', '19.823194', '17.397076', '18.630251', '8.526921', '26.510477', '23.303181', '24.446741', '15.460849', '32.852143', '29.329836', '30.474514', '22.498488', '39.882600', '36.018252', '37.350774', '29.464841', '45.579582', '42.047113', '43.277442', '36.398053', '53.425670', '48.476517', '49.427778', '43.354034', '59.413195', '53.990483', '55.265546', '50.309062', '64.940751', '59.779942', '61.020553', '57.271004', '70.787013', '66.214025', '67.411304', '64.176083', '75.405896', '71.235538', '72.409034']
reference_Device: [1.57547, 8.526921, 15.460849, 22.498488, 29.464841, 36.398053, 43.354034, 50.309062, 57.271004, 64.176083]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.617074', '20.202741', '18.009529', '19.396871', '8.566976', '27.287394', '24.175823', '25.348365', '15.470982', '32.763481', '29.277653', '30.489028', '22.447348', '39.103627', '35.121113', '36.481678', '29.413462', '44.953227', '41.253746', '42.612761', '36.361098', '52.479744', '47.289878', '48.296481', '43.300509', '58.616042', '53.135753', '54.325283', '50.316095', '65.054297', '59.860468', '61.214209', '57.294846', '70.848465', '66.337049', '67.494512', '64.215422', '76.267779', '71.987212', '73.116302']
reference_Device: [1.617074, 8.566976, 15.470982, 22.447348, 29.413462, 36.361098, 43.300509, 50.316095, 57.294846, 64.215422]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.578093', '19.247308', '17.128438', '18.507123', '8.530974', '26.803374', '23.425147', '24.729133', '15.511036', '33.616364', '30.224711', '31.442851', '22.514462', '40.005594', '36.188334', '37.498891', '29.416561', '44.953644', '41.315973', '42.879492', '36.380053', '53.334475', '48.349917', '49.137235', '43.315053', '58.474302', '52.976489', '54.315805', '50.324917', '64.937234', '60.169995', '61.610758', '57.254553', '69.883525', '65.243423', '66.451728', '64.182043', '75.586975', '71.301758', '72.592497']
reference_Device: [1.578093, 8.530974, 15.511036, 22.514462, 29.416561, 36.380053, 43.315053, 50.324917, 57.254553, 64.182043]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.628041', '20.055518', '17.915636', '19.228309', '8.566976', '26.938140', '23.685455', '24.922132', '15.526533', '33.590496', '29.968500', '31.280458', '22.435546', '39.074272', '35.152495', '36.611587', '29.456496', '45.794606', '42.083234', '43.391615', '36.404610', '53.571522', '48.473716', '49.533635', '43.338418', '59.338987', '53.940833', '55.216491', '50.323486', '64.942241', '59.819758', '61.131060', '57.229996', '70.079982', '65.391302', '66.564441', '64.220071', '76.068044', '72.055757', '73.256552']
reference_Device: [1.628041, 8.566976, 15.526533, 22.435546, 29.456496, 36.40461, 43.338418, 50.323486, 57.229996, 64.220071]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.586437', '19.410014', '17.202169', '18.509194', '8.586526', '27.485758', '24.354368', '25.317401', '15.499949', '33.007622', '29.383868', '30.635893', '22.455096', '39.171904', '35.327882', '36.754519', '29.412508', '45.017242', '41.281134', '42.672902', '36.397099', '53.312242', '48.039258', '49.072504', '43.362975', '59.353411', '53.883910', '55.071771', '50.284028', '64.412773', '59.219182', '60.461938', '57.288051', '70.796549', '65.849543', '67.227006', '64.218998', '76.612473', '72.321653', '73.594928']
reference_Device: [1.586437, 8.586526, 15.499949, 22.455096, 29.412508, 36.397099, 43.362975, 50.284028, 57.288051, 64.218998]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.628637', '20.293161', '18.009752', '19.384369', '8.555889', '27.455270', '24.243444', '25.365293', '15.489578', '32.716990', '29.231966', '30.426741', '22.463560', '39.192468', '35.256833', '36.664128', '29.462934', '47.370732', '42.725027', '43.389231', '36.397576', '53.373814', '48.407733', '49.377024', '43.349862', '59.597492', '53.911030', '55.222750', '50.276160', '64.460278', '59.289336', '60.660541', '57.276607', '70.616484', '66.179812', '67.309260', '64.167380', '75.492740', '71.281195', '72.741210']
reference_Device: [1.628637, 8.555889, 15.489578, 22.46356, 29.462934, 36.397576, 43.349862, 50.27616, 57.276607, 64.16738]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.630664', '20.251080', '17.947420', '19.483000', '8.534074', '26.713490', '23.431078', '24.636000', '15.655041', '35.542578', '31.975985', '33.239126', '22.449970', '39.300710', '35.151005', '36.496490', '29.410481', '45.063347', '41.247636', '42.497993', '36.397099', '53.376913', '48.596263', '49.300283', '43.364286', '59.620202', '54.248273', '55.388987', '50.313830', '65.112293', '59.688210', '60.970247', '57.230115', '69.862306', '65.277278', '66.611230', '64.209104', '76.375544', '72.014511', '73.260248']
reference_Device: [1.630664, 8.534074, 15.655041, 22.44997, 29.410481, 36.397099, 43.364286, 50.31383, 57.230115, 64.209104]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.629114', '20.200819', '18.012926', '19.315749', '8.555412', '27.256876', '24.070144', '25.232881', '15.505910', '33.670872', '29.929101', '31.250983', '22.493482', '39.966732', '36.226779', '37.561506', '29.401541', '44.957489', '41.208416', '42.406142', '36.378622', '52.473426', '47.322243', '48.428357', '43.356538', '59.437513', '53.963184', '55.256486', '50.313473', '65.127552', '59.934795', '61.213970', '57.232976', '69.802761', '65.227568', '66.531777', '64.254045', '76.203525', '71.957707', '73.340297']
reference_Device: [1.629114, 8.555412, 15.50591, 22.493482, 29.401541, 36.378622, 43.356538, 50.313473, 57.232976, 64.254045]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.632571', '20.118371', '17.992869', '19.341946', '8.507133', '26.528865', '23.235515', '25.500581', '15.529990', '33.593237', '30.107975', '31.246096', '22.446513', '39.094001', '35.163879', '36.526620', '29.397011', '44.868141', '41.257739', '42.582005', '36.378145', '52.454472', '47.217369', '48.384160', '43.312073', '58.397830', '52.919269', '54.206550', '50.306559', '64.308286', '59.074223', '60.225189', '57.266593', '70.640028', '66.064954', '67.192376', '64.232588', '76.298952', '72.210789', '73.219180']
reference_Device: [1.632571, 8.507133, 15.52999, 22.446513, 29.397011, 36.378145, 43.312073, 50.306559, 57.266593, 64.232588]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

arraybench_(27)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
The Overheads extracted:

{'TARGET_DEVICE_27': [], 'PRIVATE_DEVICE_27': [], 'FIRSTPRIVATE_DEVICE_27': []}
Performance mean time:

['1.586437', '19.434616', '17.240182', '18.601492', '8.553624', '26.477188', '23.311749', '24.489433', '15.489578', '32.865524', '29.308766', '30.533254', '22.491574', '39.801121', '35.878956', '37.336379', '29.376984', '44.918507', '41.319698', '42.503983', '36.354542', '52.509487', '47.258168', '48.475266', '43.458343', '60.930252', '55.711567', '57.030439', '50.318003', '65.143943', '59.935033', '61.196744', '57.303429', '70.702493', '65.603495', '67.092538', '64.235568', '76.590002', '72.352767', '73.450983']
reference_Device: [1.586437, 8.553624, 15.489578, 22.491574, 29.376984, 36.354542, 43.458343, 50.318003, 57.303429, 64.235568]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.631618', '20.246744', '20.498037', '91.114223', '8.527994', '26.520014', '26.188135', '96.134245', '15.524030', '33.685625', '32.763004', '102.962494', '22.480249', '39.759636', '38.216114', '108.833551', '29.402494', '45.012623', '43.564320', '114.088416', '36.385417', '53.021550', '50.933003', '120.674253', '43.365479', '59.653759', '56.745052', '126.937032', '50.307631', '65.044284', '62.100530', '132.581115', '57.233095', '70.113719', '67.558169', '138.086081', '64.235926', '76.219261', '74.411988', '144.747496']
reference_Device: [1.631618, 8.527994, 15.52403, 22.480249, 29.402494, 36.385417, 43.365479, 50.307631, 57.233095, 64.235926]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.587987', '19.575700', '19.511461', '90.574801', '8.523464', '26.612520', '25.870442', '96.385002', '15.492558', '32.974988', '32.088399', '102.319002', '22.463202', '39.031982', '37.603021', '107.972622', '29.387593', '45.034736', '43.514967', '114.220500', '36.360025', '52.602291', '50.289989', '120.070577', '43.312073', '58.594525', '55.460930', '125.833035', '50.273418', '64.210296', '61.212540', '131.687641', '57.263494', '70.738077', '68.276048', '138.649464', '64.175844', '75.542212', '73.484898', '143.700004']
reference_Device: [1.587987, 8.523464, 15.492558, 22.463202, 29.387593, 36.360025, 43.312073, 50.273418, 57.263494, 64.175844]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.585126', '19.420624', '19.567251', '90.250969', '8.516908', '26.673883', '26.130438', '96.348226', '15.509963', '33.719212', '32.630444', '102.997899', '22.492528', '39.722800', '38.261056', '108.791947', '29.463530', '47.370076', '45.975924', '115.208030', '36.398530', '53.359270', '50.835490', '120.599031', '43.325543', '58.626711', '55.630565', '125.796556', '50.264120', '64.493001', '61.446071', '131.989121', '57.274580', '70.454776', '68.186998', '138.576746', '64.192653', '75.555325', '73.511004', '143.690944']
reference_Device: [1.585126, 8.516908, 15.509963, 22.492528, 29.46353, 36.39853, 43.325543, 50.26412, 57.27458, 64.192653]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.590967', '19.503146', '19.668341', '90.450406', '8.585334', '27.399391', '26.970029', '97.104549', '15.526533', '33.692151', '32.634974', '102.855563', '22.503972', '39.873093', '38.771749', '109.242201', '29.447079', '45.710474', '44.497848', '114.905357', '36.381006', '53.175271', '50.822616', '120.679021', '43.306947', '58.721781', '55.546522', '125.960469', '50.289035', '64.410567', '61.466932', '131.906033', '57.260513', '70.630252', '68.578959', '139.169097', '64.211130', '76.202035', '74.388623', '144.582033']
reference_Device: [1.590967, 8.585334, 15.526533, 22.503972, 29.447079, 36.381006, 43.306947, 50.289035, 57.260513, 64.21113]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.605511', '19.467324', '19.726038', '90.420544', '8.537412', '26.737481', '26.395917', '96.498072', '15.533924', '33.770502', '32.706499', '103.145719', '22.447467', '39.111286', '37.530899', '108.025551', '29.429436', '45.746773', '44.499993', '115.183592', '36.399961', '53.253591', '50.990105', '120.804191', '43.308020', '58.481753', '55.353999', '125.790119', '50.294638', '64.203024', '61.246395', '131.699085', '57.275414', '70.758939', '68.539023', '138.716340', '64.204931', '76.484084', '74.528456', '144.699335']
reference_Device: [1.605511, 8.537412, 15.533924, 22.447467, 29.429436, 36.399961, 43.30802, 50.294638, 57.275414, 64.204931]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.585007', '19.535542', '19.393563', '90.375066', '8.571267', '27.180612', '26.873112', '97.137570', '15.518546', '33.824027', '32.641649', '103.061318', '22.485852', '39.750338', '38.122892', '108.820915', '29.391527', '44.982761', '43.530107', '114.018559', '36.357522', '52.587748', '50.363898', '120.098472', '43.301344', '58.825016', '55.518746', '125.945091', '50.320148', '65.180480', '62.307477', '132.683396', '57.231069', '69.943964', '67.466021', '137.834430', '64.211011', '76.545000', '74.665546', '144.849539']
reference_Device: [1.585007, 8.571267, 15.518546, 22.485852, 29.391527, 36.357522, 43.301344, 50.320148, 57.231069, 64.211011]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

The Performance extracted:

{'reference_Device': [], 'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
The Overheads extracted:

{'TARGET_DEVICE_729': [], 'PRIVATE_DEVICE_729': [], 'FIRSTPRIVATE_DEVICE_729': []}
Performance mean time:

['1.630664', '20.138577', '20.362020', '91.091275', '8.529067', '26.719779', '26.301265', '96.399009', '15.523911', '33.645868', '32.419562', '102.791548', '22.488475', '39.981902', '38.506269', '108.946085', '29.405594', '45.121461', '43.811917', '114.227891', '36.390543', '53.204775', '50.963998', '120.697498', '43.356895', '59.503675', '56.524396', '127.032876', '50.346851', '65.349281', '62.215567', '132.764816', '57.265043', '70.404232', '68.330884', '138.651848', '64.225435', '76.247454', '74.333310', '144.561529']
reference_Device: [1.630664, 8.529067, 15.523911, 22.488475, 29.405594, 36.390543, 43.356895, 50.346851, 57.265043, 64.225435]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 171, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 145, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise2.py", line 82, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5590392/data_reference_Device.txt'
arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20

arraybench_(729)_20
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 5590392 ON r2i7n3 CANCELLED AT 2024-04-04T19:51:04 ***
slurmstepd: error: *** STEP 5590392.178 ON r2i7n3 CANCELLED AT 2024-04-04T19:51:04 ***
