schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['398.221314', '0.997598', '7.187743', '534.273982', '1.117482', '7.321406', '663.574934', '1.240517', '7.564314', '790.524781', '1.371258', '7.573906', '919.771194', '1.493439', '7.739812', '1040.746272', '1.618811', '7.792972', '1170.276403', '1.741992', '7.966403', '1296.546459', '1.872387', '8.157343', '1426.471472', '1.996248', '8.233674', '32035.976350', '32.068193', '38.256273']
reference_Device: [398.221314, 534.273982, 663.574934, 790.524781, 919.771194, 1040.746272, 1170.276403, 1296.546459, 1426.471472, 32035.97635]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/0/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.691368', '1.000694', '7.217266', '534.392595', '1.117403', '7.278677', '663.623810', '1.240107', '7.449705', '790.494680', '1.370546', '7.667802', '919.107497', '1.493290', '7.427037', '1040.232480', '1.619356', '7.907655', '1169.999838', '1.741699', '7.961616', '1296.900213', '1.872228', '8.032415', '1426.000297', '1.995103', '8.191578', '32032.947242', '32.069013', '38.201809']
reference_Device: [411.691368, 534.392595, 663.62381, 790.49468, 919.107497, 1040.23248, 1169.999838, 1296.900213, 1426.000297, 32032.947242]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/1/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.608815', '1.000499', '7.277485', '533.836484', '1.117364', '7.320773', '663.639903', '1.240186', '7.444825', '790.012479', '1.370742', '7.555094', '919.093788', '1.493711', '7.700082', '1040.902436', '1.619062', '7.837992', '1169.595122', '1.741564', '7.949211', '1296.869814', '1.871837', '7.791091', '1425.759792', '1.995219', '8.239280', '32031.432688', '32.061860', '38.200915']
reference_Device: [411.608815, 533.836484, 663.639903, 790.012479, 919.093788, 1040.902436, 1169.595122, 1296.869814, 1425.759792, 32031.432688]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/2/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.587358', '1.001416', '7.267501', '533.989072', '1.117880', '7.341634', '663.625896', '1.240186', '7.447898', '790.096223', '1.370381', '7.264055', '919.502676', '1.493436', '7.701702', '1040.869057', '1.618695', '7.836502', '1170.256138', '1.741447', '7.904917', '1296.876073', '1.871693', '8.061640', '1426.193714', '1.995843', '8.199140', '32033.851147', '32.069385', '38.261265']
reference_Device: [411.587358, 533.989072, 663.625896, 790.096223, 919.502676, 1040.869057, 1170.256138, 1296.876073, 1426.193714, 32033.851147]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/3/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.783755', '1.001777', '7.233992', '533.541143', '1.117694', '7.461943', '663.264990', '1.240557', '7.845704', '790.071189', '1.370604', '7.591881', '919.525325', '1.493457', '7.752888', '1040.946245', '1.618690', '7.890332', '1170.307398', '1.741992', '7.917024', '1297.208667', '1.872615', '8.126348', '1426.070333', '1.996052', '8.213054', '32030.328810', '32.077432', '38.184077']
reference_Device: [411.783755, 533.541143, 663.26499, 790.071189, 919.525325, 1040.946245, 1170.307398, 1297.208667, 1426.070333, 32030.32881]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/4/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.617458', '1.001162', '7.151403', '533.908606', '1.117673', '7.294863', '663.623810', '1.240205', '7.417202', '789.954960', '1.370576', '7.594209', '919.506252', '1.493359', '7.684994', '1040.683687', '1.618513', '7.844213', '1170.245111', '1.741927', '7.922817', '1296.671331', '1.873085', '8.128677', '1426.221430', '1.995666', '8.218754', '32031.461000', '32.050833', '37.972182']
reference_Device: [411.617458, 533.908606, 663.62381, 789.95496, 919.506252, 1040.683687, 1170.245111, 1296.671331, 1426.22143, 32031.461]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/5/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.385000', '1.000341', '7.158443', '533.609986', '1.117638', '7.311478', '663.414001', '1.240021', '7.420089', '789.517760', '1.370418', '7.688180', '918.969810', '1.493720', '7.696003', '1040.268838', '1.619221', '7.839669', '1169.797778', '1.742127', '7.924847', '1296.524704', '1.871972', '7.980615', '1425.853670', '1.995312', '8.215010', '32028.293610', '32.070652', '38.205907']
reference_Device: [411.385, 533.609986, 663.414001, 789.51776, 918.96981, 1040.268838, 1169.797778, 1296.524704, 1425.85367, 32028.29361]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/6/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.198735', '0.999190', '7.244293', '533.848405', '1.117452', '7.331725', '663.716495', '1.240177', '7.402897', '789.470077', '1.370478', '7.686503', '918.848813', '1.494491', '8.133128', '1039.961278', '1.618420', '7.796157', '1169.582605', '1.741885', '7.923804', '1296.559870', '1.872485', '8.239541', '1425.797939', '1.996113', '8.141026', '32031.902671', '32.071918', '38.232505']
reference_Device: [411.198735, 533.848405, 663.716495, 789.470077, 918.848813, 1039.961278, 1169.582605, 1296.55987, 1425.797939, 32031.902671]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/7/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['411.751568', '1.001591', '7.192735', '534.156561', '1.117508', '7.261224', '663.347244', '1.239881', '7.458217', '789.852440', '1.370520', '7.553045', '919.685066', '1.492989', '7.718746', '1040.526330', '1.618983', '7.826090', '1170.081198', '1.742360', '8.013826', '1296.574771', '1.872224', '8.129142', '1426.167488', '1.995214', '8.242596', '32032.298744', '32.075942', '38.245022']
reference_Device: [411.751568, 534.156561, 663.347244, 789.85244, 919.685066, 1040.52633, 1170.081198, 1296.574771, 1426.167488, 32032.298744]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/8/data_reference_Device.txt'
schedbench_20

schedbench_40

schedbench_60

schedbench_80

schedbench_100

schedbench_120

schedbench_140

schedbench_160

schedbench_180

schedbench_5000

The Performance extracted:

{'reference_Device': [], 'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
The Overheads extracted:

{'STATIC_DEVICE': [], 'STATIC_MONOTONIC_DEVICE': []}
Performance mean time:

['412.168801', '1.002823', '7.251259', '534.237623', '1.117159', '7.083584', '663.827658', '1.240373', '7.399600', '790.062249', '1.370723', '7.502735', '919.215083', '1.493350', '7.760003', '1040.787697', '1.619160', '7.899683', '1170.366108', '1.742304', '7.974915', '1296.736002', '1.872675', '8.039530', '1426.121294', '1.995056', '8.229297', '32032.050192', '32.065287', '38.297176']
reference_Device: [412.168801, 534.237623, 663.827658, 790.062249, 919.215083, 1040.787697, 1170.366108, 1296.736002, 1426.121294, 32032.050192]
Traceback (most recent call last):
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 174, in <module>
    main()
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 148, in main
    analyse_data(benchmark, job, mean_times)
  File "/mnt/lustre/e1000/home/d403/d403/weiyu2024/PhDProject/epcc-openmp-microbenchmarks/openmpbench_C_v40/visualise.py", line 86, in analyse_data
    with open(file_name, 'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Analysis/9/data_reference_Device.txt'
